database:
  prefix: 'ps_'
  url: 'jdbc:mysql://127.0.0.1:3306/mc?useSSL=false&serverTimezone=UTC&autoReconnect=true&allowPublicKeyRetrieval=true&characterEncoding=utf8'
  user: mc
  password: mctest
lang: zh_cn
flarumurl: 'https://bbs.yinwurealm.org'
cancelkeywords:
  - 'cancel'
  - '取消'
  - '取消绑定'
bindcooldown:
  flarum: 30
  bilibili: 30