name: PonziScheme
main: moe.feo.ponzischeme.PonziScheme
version: 1.0
api-version: 1.20
folia-supported: true
author: Fengshuai(R_Josef)
website: ''
commands:
  ponzischeme:
    description: 'PonziScheme的主要指令.'
    aliases: [ps]
    usage: |
      /ponzischeme - 打开GUI菜单
      /ponzischeme help - 显示帮助页面s
      /ponzischeme reader - 读取手中物品
      /ponzischeme binding <flarum | bilibili> <用户名 | ID> - 绑定Flarum/B站账号
      /ponzischeme reload - 重载配置